Script.Load("lua/CHUD_GUIScripts/GUIInsight_PlayerFrames.lua")
Script.Load("lua/CHUD_GUIScripts/GUIAlienHUD.lua")
Script.Load("lua/CHUD_GUIScripts/GUIMarineHUD.lua")
Script.Load("lua/CHUD_GUIScripts/GUIExoHUD.lua")
Script.Load("lua/CHUD_GUIScripts/GUIEvent.lua")
Script.Load("lua/CHUD_GUIScripts/GUIMinimap.lua")

Script.Load("lua/CHUD_GUIScripts/GUIGameEnd.lua")
Script.Load("lua/CHUD_GUIScripts/GUIScoreboard.lua")
Script.Load("lua/CHUD_GUIScripts/GUIVoiceChat.lua")