Elixer.UseVersion( kCHUDElixerVersion ) 

Script.Load("lua/CHUD_GUIScripts/GUIAlienHUD.lua")
Script.Load("lua/CHUD_GUIScripts/GUIMarineHUD.lua")
Script.Load("lua/CHUD_GUIScripts/GUIExoHUD.lua")
Script.Load("lua/CHUD_GUIScripts/GUIEvent.lua")
Script.Load("lua/CHUD_GUIScripts/GUIMinimap.lua") // Comm stuff is here
Script.Load("lua/CHUD_GUIScripts/GUIMinimapConnection.lua")
Script.Load("lua/CHUD_GUIScripts/GUIProgressBar.lua")
Script.Load("lua/CHUD_GUIScripts/GUIAlienBuyMenu.lua")
Script.Load("lua/CHUD_GUIScripts/GUIGorgeBuildMenu.lua")
Script.Load("lua/CHUD_GUIScripts/GUIMarineBuyMenu.lua")
Script.Load("lua/CHUD_GUIScripts/GUIWorldText.lua")
Script.Load("lua/CHUD_GUIScripts/GUIWaypoints.lua")
Script.Load("lua/CHUD_GUIScripts/GUIUnitStatus.lua")
Script.Load("lua/CHUD_GUIScripts/GUIRequestMenu.lua")
Script.Load("lua/CHUD_GUIScripts/GUISensorBlips.lua")
Script.Load("lua/CHUD_GUIScripts/GUIPickups.lua")
Script.Load("lua/CHUD_GUIScripts/GUIGameEnd.lua")
Script.Load("lua/CHUD_GUIScripts/GUIScoreboard.lua")
Script.Load("lua/CHUD_GUIScripts/GUINotifications.lua")
Script.Load("lua/CHUD_GUIScripts/GUIDeathMessages.lua")

// I suppose these aren't really GUIScripts, but... they still draw stuff on screen? :D
Script.Load("lua/CHUD_GUIScripts/GhostModel.lua")