Elixer.UseVersion( kCHUDElixerVersion )

Script.Load("lua/NS2Plus/GUIScripts/GUIAlienHUD.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIMarineHUD.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIExoHUD.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIEvent.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIMinimap.lua") // Comm stuff is here
Script.Load("lua/NS2Plus/GUIScripts/GUIMinimapConnection.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIProgressBar.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIAlienBuyMenu.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIGorgeBuildMenu.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIMarineBuyMenu.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIWorldText.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIWaypoints.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIUnitStatus.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIRequestMenu.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUISensorBlips.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIPickups.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIScoreboard.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUINotifications.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIDeathMessages.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUICrosshair.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIHoverTooltip.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUICommanderAlerts.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIInsight_Overhead.lua")
Script.Load("lua/NS2Plus/GUIScripts/GUIInventory.lua")

GetGUIManager():CreateGUIScript("NS2Plus/Client/CHUDGUI_DeathStats")
GetGUIManager():CreateGUIScript("NS2Plus/Client/CHUDGUI_EndStats")

// I suppose these aren't really GUIScripts, but... they still draw stuff on screen? :D
Script.Load("lua/NS2Plus/GUIScripts/GhostModel.lua")